add names of the provider nodes to the logs and output
golemfactory/ray-on-golem pull request #129
Opened 2023-11-29 13:52 UTC by shadeofblue

2023-11-29 15:06 UTC, lucekdudek approved these changes

2023-11-29 16:03 UTC, approxit requested changes

2023-11-29 16:03 UTC, approxit commented on ray_on_golem/server/services/golem/golem.py
> +        await add_state_log(f"[4/9] Deploying image...")
`f` is not needed.

2023-11-29 16:03 UTC, approxit commented on ray_on_golem/server/services/golem/golem.py
> +            f"{await self._get_provider_desc(context)}, {ip=}, {context.activity=}"
Using `await` expressions inside of f-string is too much for my taste. It's better to have separate variable for readability.

2023-11-30 08:50 UTC, shadeofblue commented on ray_on_golem/server/services/golem/golem.py
> +            f"{await self._get_provider_desc(context)}, {ip=}, {context.activity=}"
is this really about _tastes_ now? :(

2023-11-30 08:58 UTC, shadeofblue commented on ray_on_golem/server/services/golem/golem.py
> +            f"{await self._get_provider_desc(context)}, {ip=}, {context.activity=}"
but so be it ¯\_(ツ)_/¯

2023-11-30 08:58 UTC, shadeofblue commented on ray_on_golem/server/services/golem/golem.py
> +        await add_state_log(f"[4/9] Deploying image...")
updated

2023-11-30 09:54 UTC, approxit approved these changes

2023-11-30 09:54 UTC, merged